// <auto-generated />
namespace datezite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tbxtillvanligt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tbxtillvanligt));
        
        string IMigrationMetadata.Id
        {
            get { return "201901101803089_tbxtillvanligt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
